### ISSUE TITLE
Testdriver: more logs

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#311]
- [x] shortened event logs #312 
- [x] dump cluster definition and test script to test logs #313
- [x] K3s agent logs as build artifacts #314
To provide additional control plane logs for the mK8s platforms, we create a separate task
