### ISSUE TITLE
Replicated Demo

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#484]
see https://github.com/stackabletech/issues/issues/564
```[tasklist]
### Tasks
- [x] Experiment with Replicated locally
- [ ] figure out how a non-Terraform/Ansible cluster fits into T2
- [ ] Implementation
- [ ] Test
- [ ] Documentation
- [ ] Integration (Infra repo)
```

**Comment by backstreetkiwi** [comment]
Demo up and running
Missing:
- Select Operator version
- Slack notification
- Enough resources on replicated.com to launch real tests
- select custom test suite
- label test run in Jenkins according to selected values
- vector agent to forward logs to our OpenSearch

**Comment by backstreetkiwi** [comment]
Due to the re-engineering of Jenkins, all of this is commodity now :-)
