### ISSUE TITLE
Spike: T2 meets EC2

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#87]
We want to support Amazon EC2 as another cloud to work with T2.

In this task, we want to explore how that can be achieved.

- [x] exploration of EC2 (Tutorials)
- [x] Terraform w/ EC2 (Tutorials)
- [x] rebuild NAT/protected nodes (infra)structure w/ EC2
- [x] rebuild JumpHost infrastructure w/ EC2
- [x] DNS/Hostnames
- [x] Wireguard (continued in #98)
- [x] root-user (?)
- [x] short VPC name
- [x] CPU/Disk stuff from cluster definition (continued in #99)
- [x] Operators
- [x] Agent
- [x] version information
- [x] Create different Templates for CentOS8 / Debian 10 (continued in #100)
- [x] Make sure that changes to common modules (TF/Ansible) do not affect existing templates negatively

**Comment by backstreetkiwi** [comment]
Great tutorial: https://dev.betterdoc.org/infrastructure/2020/02/04/setting-up-a-nat-gateway-on-aws-using-terraform.html

**Comment by backstreetkiwi** [comment]
Spike is finished, branch will not be merged as side-effects on existing templates could happen.

**Comment by backstreetkiwi** [comment]
Thoroughly tested the "old" clusters used in the integration tests. The tests were a little flaky, but the problem there seemed to be (again...) SSH connectivity
